/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IERC1155ReceiverMock,
  IERC1155ReceiverMockInterface,
} from "../../../mocks/MockNFTs.sol/IERC1155ReceiverMock";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "operator",
        type: "address",
      },
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "onERC1155Received",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IERC1155ReceiverMock__factory {
  static readonly abi = _abi;
  static createInterface(): IERC1155ReceiverMockInterface {
    return new Interface(_abi) as IERC1155ReceiverMockInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IERC1155ReceiverMock {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IERC1155ReceiverMock;
  }
}
