/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IERC721ReceiverMock,
  IERC721ReceiverMockInterface,
} from "../../../mocks/MockNFTs.sol/IERC721ReceiverMock";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "operator",
        type: "address",
      },
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "onERC721Received",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IERC721ReceiverMock__factory {
  static readonly abi = _abi;
  static createInterface(): IERC721ReceiverMockInterface {
    return new Interface(_abi) as IERC721ReceiverMockInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IERC721ReceiverMock {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IERC721ReceiverMock;
  }
}
