var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/my-auctions/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1qyhwis._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1n3w9lb._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0kko42y._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0xpcv9w._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0ayp11t._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0q-w892.js")
R.c("server/chunks/ssr/_local-product-e2e__next-internal_server_app_my-auctions_page_actions_1j7gv2e.js")
R.m(50820)
module.exports=R.m(50820).exports
