/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IBlindBid,
  IBlindBidInterface,
} from "../../MaliciousReceiver.sol/IBlindBid";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "auctionId",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "commitment",
        type: "bytes32",
      },
    ],
    name: "commitBid",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "withdrawRefund",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IBlindBid__factory {
  static readonly abi = _abi;
  static createInterface(): IBlindBidInterface {
    return new Interface(_abi) as IBlindBidInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IBlindBid {
    return new Contract(address, _abi, runner) as unknown as IBlindBid;
  }
}
