/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  AddressLike,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  MaliciousReceiver,
  MaliciousReceiverInterface,
} from "../../MaliciousReceiver.sol/MaliciousReceiver";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_target",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "attack",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "attackCount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "auctionId",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "commitment",
        type: "bytes32",
      },
    ],
    name: "doCommit",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "reentrancyAttempted",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "target",
    outputs: [
      {
        internalType: "contract IBlindBid",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

const _bytecode =
  "0x60a03461008057601f61038838819003918201601f19168301916001600160401b038311848410176100855780849260209460405283398101031261008057516001600160a01b03811690819003610080576080526040516102ec908161009c8239608051818181604c015281816101320152818161017701526101fc0152f35b600080fd5b634e487b7160e01b600052604160045260246000fdfe6080604090808252600490813610156100b6575b50361561001f57600080fd5b600091825460001981146100a35760018091018085551461003c57005b6001805460ff19168117905582917f00000000000000000000000000000000000000000000000000000000000000006001600160a01b031691823b1561009e575180948193630443e21d60e21b83525af161009357005b61009c9061028c565b005b505050fd5b634e487b7160e01b845260118352602484fd5b600090813560e01c908163407c282114610272575080634c9b872f146101ed5780639e5faafc14610161578063d4b839921461011d5763fb160c2d0361001357823461011957816003193601126101195760209060ff6001541690519015158152f35b5080fd5b508234610119578160031936011261011957517f00000000000000000000000000000000000000000000000000000000000000006001600160a01b03168152602090f35b50809183346101e957826003193601126101e9577f00000000000000000000000000000000000000000000000000000000000000006001600160a01b031691823b1561009e578151630443e21d60e21b81529284918491829084905af19081156101e057506101cd5750f35b6101d69061028c565b6101dd5780f35b80fd5b513d84823e3d90fd5b5050fd5b50918060031936011261026e577f00000000000000000000000000000000000000000000000000000000000000006001600160a01b0316918390833b15610119576044835180958193639468cb6160e01b8352803590830152602435602483015234905af19081156101e05750610262575080f35b61026b9061028c565b80f35b8280fd5b905034610119578160031936011261011957602091548152f35b67ffffffffffffffff81116102a057604052565b634e487b7160e01b600052604160045260246000fdfea2646970667358221220099402fa00a8e1c56bada9b0681e9094ab862eac21eac8aaa8003840424b656564736f6c63430008140033";

type MaliciousReceiverConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MaliciousReceiverConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MaliciousReceiver__factory extends ContractFactory {
  constructor(...args: MaliciousReceiverConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    _target: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(_target, overrides || {});
  }
  override deploy(
    _target: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(_target, overrides || {}) as Promise<
      MaliciousReceiver & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MaliciousReceiver__factory {
    return super.connect(runner) as MaliciousReceiver__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MaliciousReceiverInterface {
    return new Interface(_abi) as MaliciousReceiverInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MaliciousReceiver {
    return new Contract(address, _abi, runner) as unknown as MaliciousReceiver;
  }
}
