var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/analytics/views/route.js")
R.c("server/chunks/node_modules_1mp09po._.js")
R.c("server/chunks/node_modules_viem__esm_1zk-w-j._.js")
R.c("server/chunks/node_modules_@noble_curves_esm_secp256k1_1tfwh57.js")
R.c("server/chunks/[root-of-the-server]__1xzaezm._.js")
R.c("server/chunks/node_modules_1m8tbv-._.js")
R.c("server/chunks/node_modules_viem__esm_clients_createPublicClient_1fd78r6.js")
R.c("server/chunks/[root-of-the-server]__15bjnu5._.js")
R.c("server/chunks/node_modules_next_1zc5q0a._.js")
R.c("server/chunks/_1ad_899._.js")
R.c("server/chunks/1fju__next-internal_server_app_api_analytics_views_route_actions_16k97nu.js")
R.m(24350)
module.exports=R.m(24350).exports
