/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IERC721Veil,
  IERC721VeilInterface,
} from "../../VeilNFTV4.sol/IERC721Veil";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "ownerOf",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "safeTransferFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IERC721Veil__factory {
  static readonly abi = _abi;
  static createInterface(): IERC721VeilInterface {
    return new Interface(_abi) as IERC721VeilInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IERC721Veil {
    return new Contract(address, _abi, runner) as unknown as IERC721Veil;
  }
}
