/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MaliciousReceiverInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "attack"
      | "attackCount"
      | "doCommit"
      | "reentrancyAttempted"
      | "target"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "attack", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "attackCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "doCommit",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reentrancyAttempted",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "target", values?: undefined): string;

  decodeFunctionResult(functionFragment: "attack", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "attackCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "doCommit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reentrancyAttempted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "target", data: BytesLike): Result;
}

export interface MaliciousReceiver extends BaseContract {
  connect(runner?: ContractRunner | null): MaliciousReceiver;
  waitForDeployment(): Promise<this>;

  interface: MaliciousReceiverInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  attack: TypedContractMethod<[], [void], "nonpayable">;

  attackCount: TypedContractMethod<[], [bigint], "view">;

  doCommit: TypedContractMethod<
    [auctionId: BigNumberish, commitment: BytesLike],
    [void],
    "payable"
  >;

  reentrancyAttempted: TypedContractMethod<[], [boolean], "view">;

  target: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "attack"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "attackCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "doCommit"
  ): TypedContractMethod<
    [auctionId: BigNumberish, commitment: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "reentrancyAttempted"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "target"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
