var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/agent/v1/auctions/[id]/route.js")
R.c("server/chunks/node_modules_0g5uwwi._.js")
R.c("server/chunks/node_modules_viem__esm_1zk-w-j._.js")
R.c("server/chunks/[root-of-the-server]__13_azzi._.js")
R.c("server/chunks/node_modules_@noble_curves_esm_secp256k1_1tfwh57.js")
R.c("server/chunks/_1ad_899._.js")
R.c("server/chunks/[root-of-the-server]__15bjnu5._.js")
R.c("server/chunks/node_modules_1m8tbv-._.js")
R.c("server/chunks/node_modules_viem__esm_clients_createPublicClient_1fd78r6.js")
R.c("server/chunks/1fju__next-internal_server_app_api_agent_v1_auctions_[id]_route_actions_0q7l6-5.js")
R.m(49099)
module.exports=R.m(49099).exports
