var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/my-bids/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0in0j8k._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1n3w9lb._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0kko42y._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0xpcv9w._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0ayp11t._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0q-w892.js")
R.c("server/chunks/ssr/_local-product-e2e__next-internal_server_app_my-bids_page_actions_1sss260.js")
R.m(33907)
module.exports=R.m(33907).exports
