var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/auctions/[id]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1jsfpu4._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1n3w9lb._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0kko42y._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0xpcv9w._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0ayp11t._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0q-w892.js")
R.c("server/chunks/ssr/_local-product-e2e__next-internal_server_app_auctions_[id]_page_actions_0sw508r.js")
R.m(32040)
module.exports=R.m(32040).exports
