/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC1155ReceiverMock } from "./IERC1155ReceiverMock";
export type { IERC721ReceiverMock } from "./IERC721ReceiverMock";
export type { MockERC1155 } from "./MockERC1155";
export type { MockERC721 } from "./MockERC721";
