/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface BlindBidInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "auctionBidders"
      | "auctionCount"
      | "auctions"
      | "commitBid"
      | "commitments"
      | "computeCommitment"
      | "createAuction"
      | "getAuctionState"
      | "pendingRefunds"
      | "revealBid"
      | "settleAuction"
      | "withdrawRefund"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AuctionCreated"
      | "AuctionSettled"
      | "BidCommitted"
      | "BidRevealed"
      | "RefundAvailable"
      | "RefundClaimed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "auctionBidders",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "auctionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "auctions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "commitBid",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "commitments",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "computeCommitment",
    values: [BigNumberish, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createAuction",
    values: [string, string, string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAuctionState",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingRefunds",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revealBid",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "settleAuction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawRefund",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "auctionBidders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "auctionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "auctions", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "commitBid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "commitments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "computeCommitment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAuctionState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingRefunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revealBid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "settleAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawRefund",
    data: BytesLike
  ): Result;
}

export namespace AuctionCreatedEvent {
  export type InputTuple = [
    auctionId: BigNumberish,
    seller: AddressLike,
    itemName: string,
    startingPrice: BigNumberish,
    commitEndTime: BigNumberish,
    revealEndTime: BigNumberish
  ];
  export type OutputTuple = [
    auctionId: bigint,
    seller: string,
    itemName: string,
    startingPrice: bigint,
    commitEndTime: bigint,
    revealEndTime: bigint
  ];
  export interface OutputObject {
    auctionId: bigint;
    seller: string;
    itemName: string;
    startingPrice: bigint;
    commitEndTime: bigint;
    revealEndTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuctionSettledEvent {
  export type InputTuple = [
    auctionId: BigNumberish,
    winner: AddressLike,
    winningPrice: BigNumberish,
    secondHighestBid: BigNumberish
  ];
  export type OutputTuple = [
    auctionId: bigint,
    winner: string,
    winningPrice: bigint,
    secondHighestBid: bigint
  ];
  export interface OutputObject {
    auctionId: bigint;
    winner: string;
    winningPrice: bigint;
    secondHighestBid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BidCommittedEvent {
  export type InputTuple = [
    auctionId: BigNumberish,
    bidder: AddressLike,
    commitment: BytesLike,
    deposit: BigNumberish
  ];
  export type OutputTuple = [
    auctionId: bigint,
    bidder: string,
    commitment: string,
    deposit: bigint
  ];
  export interface OutputObject {
    auctionId: bigint;
    bidder: string;
    commitment: string;
    deposit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BidRevealedEvent {
  export type InputTuple = [
    auctionId: BigNumberish,
    bidder: AddressLike,
    maxBid: BigNumberish,
    isCurrentHighest: boolean
  ];
  export type OutputTuple = [
    auctionId: bigint,
    bidder: string,
    maxBid: bigint,
    isCurrentHighest: boolean
  ];
  export interface OutputObject {
    auctionId: bigint;
    bidder: string;
    maxBid: bigint;
    isCurrentHighest: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundAvailableEvent {
  export type InputTuple = [account: AddressLike, amount: BigNumberish];
  export type OutputTuple = [account: string, amount: bigint];
  export interface OutputObject {
    account: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundClaimedEvent {
  export type InputTuple = [account: AddressLike, amount: BigNumberish];
  export type OutputTuple = [account: string, amount: bigint];
  export interface OutputObject {
    account: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BlindBid extends BaseContract {
  connect(runner?: ContractRunner | null): BlindBid;
  waitForDeployment(): Promise<this>;

  interface: BlindBidInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  auctionBidders: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;

  auctionCount: TypedContractMethod<[], [bigint], "view">;

  auctions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        id: bigint;
        seller: string;
        itemName: string;
        description: string;
        imageURI: string;
        startingPrice: bigint;
        commitEndTime: bigint;
        revealEndTime: bigint;
        state: bigint;
        highestBidder: string;
        highestBid: bigint;
        secondHighestBid: bigint;
        bidderCount: bigint;
        revealedCount: bigint;
        finalTxHash: string;
      }
    ],
    "view"
  >;

  commitBid: TypedContractMethod<
    [auctionId: BigNumberish, commitment: BytesLike],
    [void],
    "payable"
  >;

  commitments: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [string, bigint, boolean, bigint] & {
        commitment: string;
        deposit: bigint;
        revealed: boolean;
        maxBid: bigint;
      }
    ],
    "view"
  >;

  computeCommitment: TypedContractMethod<
    [
      auctionId: BigNumberish,
      bidder: AddressLike,
      maxBid: BigNumberish,
      secret: BytesLike
    ],
    [string],
    "view"
  >;

  createAuction: TypedContractMethod<
    [
      itemName: string,
      description: string,
      imageURI: string,
      startingPrice: BigNumberish,
      commitDuration: BigNumberish,
      revealDuration: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  getAuctionState: TypedContractMethod<
    [auctionId: BigNumberish],
    [bigint],
    "view"
  >;

  pendingRefunds: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  revealBid: TypedContractMethod<
    [auctionId: BigNumberish, maxBid: BigNumberish, secret: BytesLike],
    [void],
    "nonpayable"
  >;

  settleAuction: TypedContractMethod<
    [auctionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawRefund: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "auctionBidders"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "auctionCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "auctions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        id: bigint;
        seller: string;
        itemName: string;
        description: string;
        imageURI: string;
        startingPrice: bigint;
        commitEndTime: bigint;
        revealEndTime: bigint;
        state: bigint;
        highestBidder: string;
        highestBid: bigint;
        secondHighestBid: bigint;
        bidderCount: bigint;
        revealedCount: bigint;
        finalTxHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "commitBid"
  ): TypedContractMethod<
    [auctionId: BigNumberish, commitment: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "commitments"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [string, bigint, boolean, bigint] & {
        commitment: string;
        deposit: bigint;
        revealed: boolean;
        maxBid: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "computeCommitment"
  ): TypedContractMethod<
    [
      auctionId: BigNumberish,
      bidder: AddressLike,
      maxBid: BigNumberish,
      secret: BytesLike
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "createAuction"
  ): TypedContractMethod<
    [
      itemName: string,
      description: string,
      imageURI: string,
      startingPrice: BigNumberish,
      commitDuration: BigNumberish,
      revealDuration: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAuctionState"
  ): TypedContractMethod<[auctionId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "pendingRefunds"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "revealBid"
  ): TypedContractMethod<
    [auctionId: BigNumberish, maxBid: BigNumberish, secret: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "settleAuction"
  ): TypedContractMethod<[auctionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawRefund"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "AuctionCreated"
  ): TypedContractEvent<
    AuctionCreatedEvent.InputTuple,
    AuctionCreatedEvent.OutputTuple,
    AuctionCreatedEvent.OutputObject
  >;
  getEvent(
    key: "AuctionSettled"
  ): TypedContractEvent<
    AuctionSettledEvent.InputTuple,
    AuctionSettledEvent.OutputTuple,
    AuctionSettledEvent.OutputObject
  >;
  getEvent(
    key: "BidCommitted"
  ): TypedContractEvent<
    BidCommittedEvent.InputTuple,
    BidCommittedEvent.OutputTuple,
    BidCommittedEvent.OutputObject
  >;
  getEvent(
    key: "BidRevealed"
  ): TypedContractEvent<
    BidRevealedEvent.InputTuple,
    BidRevealedEvent.OutputTuple,
    BidRevealedEvent.OutputObject
  >;
  getEvent(
    key: "RefundAvailable"
  ): TypedContractEvent<
    RefundAvailableEvent.InputTuple,
    RefundAvailableEvent.OutputTuple,
    RefundAvailableEvent.OutputObject
  >;
  getEvent(
    key: "RefundClaimed"
  ): TypedContractEvent<
    RefundClaimedEvent.InputTuple,
    RefundClaimedEvent.OutputTuple,
    RefundClaimedEvent.OutputObject
  >;

  filters: {
    "AuctionCreated(uint256,address,string,uint256,uint256,uint256)": TypedContractEvent<
      AuctionCreatedEvent.InputTuple,
      AuctionCreatedEvent.OutputTuple,
      AuctionCreatedEvent.OutputObject
    >;
    AuctionCreated: TypedContractEvent<
      AuctionCreatedEvent.InputTuple,
      AuctionCreatedEvent.OutputTuple,
      AuctionCreatedEvent.OutputObject
    >;

    "AuctionSettled(uint256,address,uint256,uint256)": TypedContractEvent<
      AuctionSettledEvent.InputTuple,
      AuctionSettledEvent.OutputTuple,
      AuctionSettledEvent.OutputObject
    >;
    AuctionSettled: TypedContractEvent<
      AuctionSettledEvent.InputTuple,
      AuctionSettledEvent.OutputTuple,
      AuctionSettledEvent.OutputObject
    >;

    "BidCommitted(uint256,address,bytes32,uint256)": TypedContractEvent<
      BidCommittedEvent.InputTuple,
      BidCommittedEvent.OutputTuple,
      BidCommittedEvent.OutputObject
    >;
    BidCommitted: TypedContractEvent<
      BidCommittedEvent.InputTuple,
      BidCommittedEvent.OutputTuple,
      BidCommittedEvent.OutputObject
    >;

    "BidRevealed(uint256,address,uint256,bool)": TypedContractEvent<
      BidRevealedEvent.InputTuple,
      BidRevealedEvent.OutputTuple,
      BidRevealedEvent.OutputObject
    >;
    BidRevealed: TypedContractEvent<
      BidRevealedEvent.InputTuple,
      BidRevealedEvent.OutputTuple,
      BidRevealedEvent.OutputObject
    >;

    "RefundAvailable(address,uint256)": TypedContractEvent<
      RefundAvailableEvent.InputTuple,
      RefundAvailableEvent.OutputTuple,
      RefundAvailableEvent.OutputObject
    >;
    RefundAvailable: TypedContractEvent<
      RefundAvailableEvent.InputTuple,
      RefundAvailableEvent.OutputTuple,
      RefundAvailableEvent.OutputObject
    >;

    "RefundClaimed(address,uint256)": TypedContractEvent<
      RefundClaimedEvent.InputTuple,
      RefundClaimedEvent.OutputTuple,
      RefundClaimedEvent.OutputObject
    >;
    RefundClaimed: TypedContractEvent<
      RefundClaimedEvent.InputTuple,
      RefundClaimedEvent.OutputTuple,
      RefundClaimedEvent.OutputObject
    >;
  };
}
