/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "BlindBid",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BlindBid__factory>;
    getContractFactory(
      name: "IBlindBid",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IBlindBid__factory>;
    getContractFactory(
      name: "MaliciousReceiver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MaliciousReceiver__factory>;
    getContractFactory(
      name: "IERC1155ReceiverMock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155ReceiverMock__factory>;
    getContractFactory(
      name: "IERC721ReceiverMock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721ReceiverMock__factory>;
    getContractFactory(
      name: "MockERC1155",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockERC1155__factory>;
    getContractFactory(
      name: "MockERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockERC721__factory>;
    getContractFactory(
      name: "IERC1155Veil",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155Veil__factory>;
    getContractFactory(
      name: "IERC721Veil",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Veil__factory>;
    getContractFactory(
      name: "VeilNFTV4",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.VeilNFTV4__factory>;
    getContractFactory(
      name: "VeilV2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.VeilV2__factory>;
    getContractFactory(
      name: "VeilV3",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.VeilV3__factory>;

    getContractAt(
      name: "BlindBid",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.BlindBid>;
    getContractAt(
      name: "IBlindBid",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IBlindBid>;
    getContractAt(
      name: "MaliciousReceiver",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MaliciousReceiver>;
    getContractAt(
      name: "IERC1155ReceiverMock",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155ReceiverMock>;
    getContractAt(
      name: "IERC721ReceiverMock",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721ReceiverMock>;
    getContractAt(
      name: "MockERC1155",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockERC1155>;
    getContractAt(
      name: "MockERC721",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockERC721>;
    getContractAt(
      name: "IERC1155Veil",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155Veil>;
    getContractAt(
      name: "IERC721Veil",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Veil>;
    getContractAt(
      name: "VeilNFTV4",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.VeilNFTV4>;
    getContractAt(
      name: "VeilV2",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.VeilV2>;
    getContractAt(
      name: "VeilV3",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.VeilV3>;

    deployContract(
      name: "BlindBid",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BlindBid>;
    deployContract(
      name: "IBlindBid",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBlindBid>;
    deployContract(
      name: "MaliciousReceiver",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MaliciousReceiver>;
    deployContract(
      name: "IERC1155ReceiverMock",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155ReceiverMock>;
    deployContract(
      name: "IERC721ReceiverMock",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721ReceiverMock>;
    deployContract(
      name: "MockERC1155",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockERC1155>;
    deployContract(
      name: "MockERC721",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockERC721>;
    deployContract(
      name: "IERC1155Veil",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155Veil>;
    deployContract(
      name: "IERC721Veil",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Veil>;
    deployContract(
      name: "VeilNFTV4",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VeilNFTV4>;
    deployContract(
      name: "VeilV2",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VeilV2>;
    deployContract(
      name: "VeilV3",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VeilV3>;

    deployContract(
      name: "BlindBid",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BlindBid>;
    deployContract(
      name: "IBlindBid",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBlindBid>;
    deployContract(
      name: "MaliciousReceiver",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MaliciousReceiver>;
    deployContract(
      name: "IERC1155ReceiverMock",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155ReceiverMock>;
    deployContract(
      name: "IERC721ReceiverMock",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721ReceiverMock>;
    deployContract(
      name: "MockERC1155",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockERC1155>;
    deployContract(
      name: "MockERC721",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockERC721>;
    deployContract(
      name: "IERC1155Veil",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155Veil>;
    deployContract(
      name: "IERC721Veil",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Veil>;
    deployContract(
      name: "VeilNFTV4",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VeilNFTV4>;
    deployContract(
      name: "VeilV2",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VeilV2>;
    deployContract(
      name: "VeilV3",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VeilV3>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
