/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface VeilV2Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "BPS_DENOMINATOR"
      | "PLATFORM_FEE_BPS"
      | "acceptDataset"
      | "auctionBidders"
      | "auctionCount"
      | "auctions"
      | "commitBid"
      | "commitments"
      | "computeCommitment"
      | "createAuction"
      | "feeRecipient"
      | "finalizeSettlement"
      | "getAuctionState"
      | "markUnderReview"
      | "pendingRefunds"
      | "requestRefund"
      | "resolveRefund"
      | "revealBid"
      | "reviewer"
      | "settleAuction"
      | "withdrawRefund"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AuctionCompleted"
      | "AuctionCreated"
      | "AuctionSettledToInspection"
      | "BidCommitted"
      | "BidRevealed"
      | "DatasetAccepted"
      | "RefundAvailable"
      | "RefundClaimed"
      | "RefundRequested"
      | "RefundResolved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BPS_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PLATFORM_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptDataset",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "auctionBidders",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "auctionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "auctions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "commitBid",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "commitments",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "computeCommitment",
    values: [BigNumberish, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createAuction",
    values: [
      string,
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "feeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeSettlement",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAuctionState",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "markUnderReview",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingRefunds",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestRefund",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveRefund",
    values: [BigNumberish, boolean, string]
  ): string;
  encodeFunctionData(
    functionFragment: "revealBid",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "reviewer", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "settleAuction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawRefund",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "BPS_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PLATFORM_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptDataset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "auctionBidders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "auctionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "auctions", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "commitBid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "commitments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "computeCommitment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeSettlement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAuctionState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "markUnderReview",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingRefunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revealBid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "reviewer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "settleAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawRefund",
    data: BytesLike
  ): Result;
}

export namespace AuctionCompletedEvent {
  export type InputTuple = [
    auctionId: BigNumberish,
    seller: AddressLike,
    sellerAmount: BigNumberish,
    platformFee: BigNumberish
  ];
  export type OutputTuple = [
    auctionId: bigint,
    seller: string,
    sellerAmount: bigint,
    platformFee: bigint
  ];
  export interface OutputObject {
    auctionId: bigint;
    seller: string;
    sellerAmount: bigint;
    platformFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuctionCreatedEvent {
  export type InputTuple = [
    auctionId: BigNumberish,
    seller: AddressLike,
    itemName: string,
    startingPrice: BigNumberish,
    commitEndTime: BigNumberish,
    revealEndTime: BigNumberish,
    inspectionDuration: BigNumberish
  ];
  export type OutputTuple = [
    auctionId: bigint,
    seller: string,
    itemName: string,
    startingPrice: bigint,
    commitEndTime: bigint,
    revealEndTime: bigint,
    inspectionDuration: bigint
  ];
  export interface OutputObject {
    auctionId: bigint;
    seller: string;
    itemName: string;
    startingPrice: bigint;
    commitEndTime: bigint;
    revealEndTime: bigint;
    inspectionDuration: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuctionSettledToInspectionEvent {
  export type InputTuple = [
    auctionId: BigNumberish,
    winner: AddressLike,
    winningPrice: BigNumberish,
    inspectionEndTime: BigNumberish
  ];
  export type OutputTuple = [
    auctionId: bigint,
    winner: string,
    winningPrice: bigint,
    inspectionEndTime: bigint
  ];
  export interface OutputObject {
    auctionId: bigint;
    winner: string;
    winningPrice: bigint;
    inspectionEndTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BidCommittedEvent {
  export type InputTuple = [
    auctionId: BigNumberish,
    bidder: AddressLike,
    commitment: BytesLike,
    deposit: BigNumberish
  ];
  export type OutputTuple = [
    auctionId: bigint,
    bidder: string,
    commitment: string,
    deposit: bigint
  ];
  export interface OutputObject {
    auctionId: bigint;
    bidder: string;
    commitment: string;
    deposit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BidRevealedEvent {
  export type InputTuple = [
    auctionId: BigNumberish,
    bidder: AddressLike,
    maxBid: BigNumberish,
    isCurrentHighest: boolean
  ];
  export type OutputTuple = [
    auctionId: bigint,
    bidder: string,
    maxBid: bigint,
    isCurrentHighest: boolean
  ];
  export interface OutputObject {
    auctionId: bigint;
    bidder: string;
    maxBid: bigint;
    isCurrentHighest: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DatasetAcceptedEvent {
  export type InputTuple = [auctionId: BigNumberish, winner: AddressLike];
  export type OutputTuple = [auctionId: bigint, winner: string];
  export interface OutputObject {
    auctionId: bigint;
    winner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundAvailableEvent {
  export type InputTuple = [account: AddressLike, amount: BigNumberish];
  export type OutputTuple = [account: string, amount: bigint];
  export interface OutputObject {
    account: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundClaimedEvent {
  export type InputTuple = [account: AddressLike, amount: BigNumberish];
  export type OutputTuple = [account: string, amount: bigint];
  export interface OutputObject {
    account: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundRequestedEvent {
  export type InputTuple = [
    auctionId: BigNumberish,
    winner: AddressLike,
    evidenceHash: string
  ];
  export type OutputTuple = [
    auctionId: bigint,
    winner: string,
    evidenceHash: string
  ];
  export interface OutputObject {
    auctionId: bigint;
    winner: string;
    evidenceHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundResolvedEvent {
  export type InputTuple = [
    auctionId: BigNumberish,
    approved: boolean,
    reason: string
  ];
  export type OutputTuple = [
    auctionId: bigint,
    approved: boolean,
    reason: string
  ];
  export interface OutputObject {
    auctionId: bigint;
    approved: boolean;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VeilV2 extends BaseContract {
  connect(runner?: ContractRunner | null): VeilV2;
  waitForDeployment(): Promise<this>;

  interface: VeilV2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BPS_DENOMINATOR: TypedContractMethod<[], [bigint], "view">;

  PLATFORM_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  acceptDataset: TypedContractMethod<
    [auctionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  auctionBidders: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;

  auctionCount: TypedContractMethod<[], [bigint], "view">;

  auctions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        string
      ] & {
        id: bigint;
        seller: string;
        itemName: string;
        description: string;
        imageURI: string;
        startingPrice: bigint;
        commitEndTime: bigint;
        revealEndTime: bigint;
        inspectionDuration: bigint;
        inspectionEndTime: bigint;
        state: bigint;
        highestBidder: string;
        highestBid: bigint;
        secondHighestBid: bigint;
        bidderCount: bigint;
        revealedCount: bigint;
        finalTxHash: string;
        evidenceHash: string;
        reviewReason: string;
      }
    ],
    "view"
  >;

  commitBid: TypedContractMethod<
    [auctionId: BigNumberish, commitment: BytesLike],
    [void],
    "payable"
  >;

  commitments: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [string, bigint, boolean, bigint] & {
        commitment: string;
        deposit: bigint;
        revealed: boolean;
        maxBid: bigint;
      }
    ],
    "view"
  >;

  computeCommitment: TypedContractMethod<
    [
      auctionId: BigNumberish,
      bidder: AddressLike,
      maxBid: BigNumberish,
      secret: BytesLike
    ],
    [string],
    "view"
  >;

  createAuction: TypedContractMethod<
    [
      itemName: string,
      description: string,
      imageURI: string,
      startingPrice: BigNumberish,
      commitDuration: BigNumberish,
      revealDuration: BigNumberish,
      inspectionDuration: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  feeRecipient: TypedContractMethod<[], [string], "view">;

  finalizeSettlement: TypedContractMethod<
    [auctionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getAuctionState: TypedContractMethod<
    [auctionId: BigNumberish],
    [bigint],
    "view"
  >;

  markUnderReview: TypedContractMethod<
    [auctionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  pendingRefunds: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  requestRefund: TypedContractMethod<
    [auctionId: BigNumberish, evidenceHash: string],
    [void],
    "nonpayable"
  >;

  resolveRefund: TypedContractMethod<
    [auctionId: BigNumberish, approved: boolean, reason: string],
    [void],
    "nonpayable"
  >;

  revealBid: TypedContractMethod<
    [auctionId: BigNumberish, maxBid: BigNumberish, secret: BytesLike],
    [void],
    "nonpayable"
  >;

  reviewer: TypedContractMethod<[], [string], "view">;

  settleAuction: TypedContractMethod<
    [auctionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawRefund: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BPS_DENOMINATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PLATFORM_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "acceptDataset"
  ): TypedContractMethod<[auctionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "auctionBidders"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "auctionCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "auctions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        string
      ] & {
        id: bigint;
        seller: string;
        itemName: string;
        description: string;
        imageURI: string;
        startingPrice: bigint;
        commitEndTime: bigint;
        revealEndTime: bigint;
        inspectionDuration: bigint;
        inspectionEndTime: bigint;
        state: bigint;
        highestBidder: string;
        highestBid: bigint;
        secondHighestBid: bigint;
        bidderCount: bigint;
        revealedCount: bigint;
        finalTxHash: string;
        evidenceHash: string;
        reviewReason: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "commitBid"
  ): TypedContractMethod<
    [auctionId: BigNumberish, commitment: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "commitments"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [string, bigint, boolean, bigint] & {
        commitment: string;
        deposit: bigint;
        revealed: boolean;
        maxBid: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "computeCommitment"
  ): TypedContractMethod<
    [
      auctionId: BigNumberish,
      bidder: AddressLike,
      maxBid: BigNumberish,
      secret: BytesLike
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "createAuction"
  ): TypedContractMethod<
    [
      itemName: string,
      description: string,
      imageURI: string,
      startingPrice: BigNumberish,
      commitDuration: BigNumberish,
      revealDuration: BigNumberish,
      inspectionDuration: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "feeRecipient"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "finalizeSettlement"
  ): TypedContractMethod<[auctionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAuctionState"
  ): TypedContractMethod<[auctionId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "markUnderReview"
  ): TypedContractMethod<[auctionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "pendingRefunds"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "requestRefund"
  ): TypedContractMethod<
    [auctionId: BigNumberish, evidenceHash: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resolveRefund"
  ): TypedContractMethod<
    [auctionId: BigNumberish, approved: boolean, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revealBid"
  ): TypedContractMethod<
    [auctionId: BigNumberish, maxBid: BigNumberish, secret: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "reviewer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "settleAuction"
  ): TypedContractMethod<[auctionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawRefund"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "AuctionCompleted"
  ): TypedContractEvent<
    AuctionCompletedEvent.InputTuple,
    AuctionCompletedEvent.OutputTuple,
    AuctionCompletedEvent.OutputObject
  >;
  getEvent(
    key: "AuctionCreated"
  ): TypedContractEvent<
    AuctionCreatedEvent.InputTuple,
    AuctionCreatedEvent.OutputTuple,
    AuctionCreatedEvent.OutputObject
  >;
  getEvent(
    key: "AuctionSettledToInspection"
  ): TypedContractEvent<
    AuctionSettledToInspectionEvent.InputTuple,
    AuctionSettledToInspectionEvent.OutputTuple,
    AuctionSettledToInspectionEvent.OutputObject
  >;
  getEvent(
    key: "BidCommitted"
  ): TypedContractEvent<
    BidCommittedEvent.InputTuple,
    BidCommittedEvent.OutputTuple,
    BidCommittedEvent.OutputObject
  >;
  getEvent(
    key: "BidRevealed"
  ): TypedContractEvent<
    BidRevealedEvent.InputTuple,
    BidRevealedEvent.OutputTuple,
    BidRevealedEvent.OutputObject
  >;
  getEvent(
    key: "DatasetAccepted"
  ): TypedContractEvent<
    DatasetAcceptedEvent.InputTuple,
    DatasetAcceptedEvent.OutputTuple,
    DatasetAcceptedEvent.OutputObject
  >;
  getEvent(
    key: "RefundAvailable"
  ): TypedContractEvent<
    RefundAvailableEvent.InputTuple,
    RefundAvailableEvent.OutputTuple,
    RefundAvailableEvent.OutputObject
  >;
  getEvent(
    key: "RefundClaimed"
  ): TypedContractEvent<
    RefundClaimedEvent.InputTuple,
    RefundClaimedEvent.OutputTuple,
    RefundClaimedEvent.OutputObject
  >;
  getEvent(
    key: "RefundRequested"
  ): TypedContractEvent<
    RefundRequestedEvent.InputTuple,
    RefundRequestedEvent.OutputTuple,
    RefundRequestedEvent.OutputObject
  >;
  getEvent(
    key: "RefundResolved"
  ): TypedContractEvent<
    RefundResolvedEvent.InputTuple,
    RefundResolvedEvent.OutputTuple,
    RefundResolvedEvent.OutputObject
  >;

  filters: {
    "AuctionCompleted(uint256,address,uint256,uint256)": TypedContractEvent<
      AuctionCompletedEvent.InputTuple,
      AuctionCompletedEvent.OutputTuple,
      AuctionCompletedEvent.OutputObject
    >;
    AuctionCompleted: TypedContractEvent<
      AuctionCompletedEvent.InputTuple,
      AuctionCompletedEvent.OutputTuple,
      AuctionCompletedEvent.OutputObject
    >;

    "AuctionCreated(uint256,address,string,uint256,uint256,uint256,uint256)": TypedContractEvent<
      AuctionCreatedEvent.InputTuple,
      AuctionCreatedEvent.OutputTuple,
      AuctionCreatedEvent.OutputObject
    >;
    AuctionCreated: TypedContractEvent<
      AuctionCreatedEvent.InputTuple,
      AuctionCreatedEvent.OutputTuple,
      AuctionCreatedEvent.OutputObject
    >;

    "AuctionSettledToInspection(uint256,address,uint256,uint256)": TypedContractEvent<
      AuctionSettledToInspectionEvent.InputTuple,
      AuctionSettledToInspectionEvent.OutputTuple,
      AuctionSettledToInspectionEvent.OutputObject
    >;
    AuctionSettledToInspection: TypedContractEvent<
      AuctionSettledToInspectionEvent.InputTuple,
      AuctionSettledToInspectionEvent.OutputTuple,
      AuctionSettledToInspectionEvent.OutputObject
    >;

    "BidCommitted(uint256,address,bytes32,uint256)": TypedContractEvent<
      BidCommittedEvent.InputTuple,
      BidCommittedEvent.OutputTuple,
      BidCommittedEvent.OutputObject
    >;
    BidCommitted: TypedContractEvent<
      BidCommittedEvent.InputTuple,
      BidCommittedEvent.OutputTuple,
      BidCommittedEvent.OutputObject
    >;

    "BidRevealed(uint256,address,uint256,bool)": TypedContractEvent<
      BidRevealedEvent.InputTuple,
      BidRevealedEvent.OutputTuple,
      BidRevealedEvent.OutputObject
    >;
    BidRevealed: TypedContractEvent<
      BidRevealedEvent.InputTuple,
      BidRevealedEvent.OutputTuple,
      BidRevealedEvent.OutputObject
    >;

    "DatasetAccepted(uint256,address)": TypedContractEvent<
      DatasetAcceptedEvent.InputTuple,
      DatasetAcceptedEvent.OutputTuple,
      DatasetAcceptedEvent.OutputObject
    >;
    DatasetAccepted: TypedContractEvent<
      DatasetAcceptedEvent.InputTuple,
      DatasetAcceptedEvent.OutputTuple,
      DatasetAcceptedEvent.OutputObject
    >;

    "RefundAvailable(address,uint256)": TypedContractEvent<
      RefundAvailableEvent.InputTuple,
      RefundAvailableEvent.OutputTuple,
      RefundAvailableEvent.OutputObject
    >;
    RefundAvailable: TypedContractEvent<
      RefundAvailableEvent.InputTuple,
      RefundAvailableEvent.OutputTuple,
      RefundAvailableEvent.OutputObject
    >;

    "RefundClaimed(address,uint256)": TypedContractEvent<
      RefundClaimedEvent.InputTuple,
      RefundClaimedEvent.OutputTuple,
      RefundClaimedEvent.OutputObject
    >;
    RefundClaimed: TypedContractEvent<
      RefundClaimedEvent.InputTuple,
      RefundClaimedEvent.OutputTuple,
      RefundClaimedEvent.OutputObject
    >;

    "RefundRequested(uint256,address,string)": TypedContractEvent<
      RefundRequestedEvent.InputTuple,
      RefundRequestedEvent.OutputTuple,
      RefundRequestedEvent.OutputObject
    >;
    RefundRequested: TypedContractEvent<
      RefundRequestedEvent.InputTuple,
      RefundRequestedEvent.OutputTuple,
      RefundRequestedEvent.OutputObject
    >;

    "RefundResolved(uint256,bool,string)": TypedContractEvent<
      RefundResolvedEvent.InputTuple,
      RefundResolvedEvent.OutputTuple,
      RefundResolvedEvent.OutputObject
    >;
    RefundResolved: TypedContractEvent<
      RefundResolvedEvent.InputTuple,
      RefundResolvedEvent.OutputTuple,
      RefundResolvedEvent.OutputObject
    >;
  };
}
