// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/auctions/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auctions/[id]">> = Specific
  const handler = {} as typeof import("../../app/auctions/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auctions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auctions">> = Specific
  const handler = {} as typeof import("../../app/auctions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/create">> = Specific
  const handler = {} as typeof import("../../app/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/how-it-works/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/how-it-works">> = Specific
  const handler = {} as typeof import("../../app/how-it-works/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/my-auctions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/my-auctions">> = Specific
  const handler = {} as typeof import("../../app/my-auctions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/my-bids/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/my-bids">> = Specific
  const handler = {} as typeof import("../../app/my-bids/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/reviewer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviewer">> = Specific
  const handler = {} as typeof import("../../app/reviewer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/seller-analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/seller-analytics">> = Specific
  const handler = {} as typeof import("../../app/seller-analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/verify/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verify/[id]">> = Specific
  const handler = {} as typeof import("../../app/verify/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/verify/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verify">> = Specific
  const handler = {} as typeof import("../../app/verify/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/agent/v1/auctions/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/v1/auctions/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/agent/v1/auctions/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/agent/v1/auctions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/v1/auctions">> = Specific
  const handler = {} as typeof import("../../app/api/agent/v1/auctions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/analytics/views/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analytics/views">> = Specific
  const handler = {} as typeof import("../../app/api/analytics/views/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/datasets/download/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/datasets/download">> = Specific
  const handler = {} as typeof import("../../app/api/datasets/download/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/datasets/inspect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/datasets/inspect">> = Specific
  const handler = {} as typeof import("../../app/api/datasets/inspect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/datasets/link/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/datasets/link">> = Specific
  const handler = {} as typeof import("../../app/api/datasets/link/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/datasets/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/datasets/upload">> = Specific
  const handler = {} as typeof import("../../app/api/datasets/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ipfs/proxy/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ipfs/proxy">> = Specific
  const handler = {} as typeof import("../../app/api/ipfs/proxy/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ipfs/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ipfs/upload">> = Specific
  const handler = {} as typeof import("../../app/api/ipfs/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reviewer/refunds/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reviewer/refunds">> = Specific
  const handler = {} as typeof import("../../app/api/reviewer/refunds/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
